# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('SQL', 'SQL'), ('Java', 'Java'), ('Python', 'Python'), ('Javascript', 'Javascript'), ('Django', 'Django'), ('C++', 'C++'), ('Ruby', 'Ruby'), ('PHP', 'PHP')], max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='categories',
        ),
        migrations.AddField(
            model_name='question',
            name='categories',
            field=models.ManyToManyField(to='qna.Tag'),
        ),
    ]
