# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_auto_20160518_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner',
            new_name='user',
        ),
    ]
