# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_auto_20160520_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='topic',
            field=models.CharField(choices=[('SQL', 'SQL'), ('Java', 'Java'), ('Python', 'Python'), ('Javascript', 'Javascript'), ('Django', 'Django'), ('C++', 'C++'), ('Ruby', 'Ruby'), ('PHP', 'PHP')], max_length=25, unique=True),
        ),
    ]
